server:
  port: ${SERVER_PORT}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  application:
    name: Slick
  threads:
    virtual:
      enabled: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE}
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: headers
  task:
    scheduling:
      pool:
        size: 4

logging:
  level:
    toy.slick.feign: debug
    org.springframework.data.mongodb.core.MongoTemplate: debug
    org.jooq.tools.LoggerListener: debug
    org.jooq.Constants: off

telegram:
  bot:
    slick:
      token: ${BOT_SLICK_TOKEN}
  chat:
    slick:
      us:
        id: ${CHAT_SLICK_US_ID}
      kr:
        id: ${CHAT_SLICK_KR_ID}

controller:
  key: ${CONTROLLER_KEY}

