server:
  port: ${SERVER_PORT}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  application:
    name: Slick
  threads:
    virtual:
      enabled: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: headers
  task:
    scheduling:
      pool:
        size: 4

logging:
  level:
    toy.slick.feign: debug
    org.jooq.tools.LoggerListener: debug

telegram:
  bot:
    slick:
      token: ${BOT_SLICK_TOKEN}
  chat:
    slick:
      id: ${CHAT_SLICK_ID}
